version: "3.7"
services:
  web-server:
    build:
      dockerfile: Dockerfile
      context: php/
    restart: unless-stopped
    volumes:
      - "./php/src/:/var/www/html/"
    ports:
      - 8123:80

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ''
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
